version: "3.9"
services:
  build_node:
    image: albs-node:latest
    privileged: true
    build:
      dockerfile: Dockerfile
      context: .
    command: "bash -c 'source env/bin/activate && ./almalinux_build_node.py -v'"
    restart: on-failure
    volumes:
      - "./volumes/node_config:/root/.config"
