version: "3.9"
services:
  build_node:
    image: avoid/albs-node
    privileged: true
    build:
      dockerfile: Dockerfile
      context: .
    command: "bash -c 'source env/bin/activate && ./almalinux_build_node.py -v'"
    restart: on-failure
    volumes:
      - "./slave-config:/root/.config"
    extra_hosts:
     - "beta-build.cloudlinux.com:192.168.246.79"
