name: pytest
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Check out repository
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: isbang/compose-action@v1.5.1
        name: Run docker-compose
        with:
          # Use this if you change something in Dockerfile
          # up-flags: --build --no-deps
          up-flags: "--pull always --no-build --no-deps"
          down-flags: "--volumes"
      - name: Run unit tests (pytest)
        run: docker-compose run -v /tmp:/tmp --no-deps build_node bash -o pipefail -c 'source
          env/bin/activate && pip3 install -r requirements.txt &&
          pytest -vv --cov-report term-missing:skip-covered
          --cov-report xml:/tmp/coverage.xml --junitxml=/tmp/pytest.xml --cov=build_node
          tests/ | tee /tmp/pytest-coverage.txt'
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        id: coverageComment
        with:
          pytest-coverage-path: /tmp/pytest-coverage.txt
          pytest-xml-coverage-path: /tmp/coverage.xml
          title: Coverage report for changed files
          badge-title: Total coverage
          hide-badge: false
          hide-report: false
          report-only-changed-files: true
          hide-comment: false
          remove-link-from-badge: false
          junitxml-path: /tmp/pytest.xml
      - name: Create the Badge
        if: ${{ github.ref == 'refs/heads/master' && steps.coverageComment.outputs.coverage }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: fc7bacd03455d19a15024e7ae1c29e24
          filename: build-node-badge__master.json
          label: Test Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: pytest
